---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check Elastic version
    shell:
      cmd: /opt/elastic/8.3.2/bin/elasticsearch --version
    changed_when: false